/*
 * @copyright (c) 2001 Chelsea Market Systems LLC
 */

package  com.chelseasystems.cs.swing.session;

import  com.chelseasystems.cr.appmgr.*;
import  com.chelseasystems.cr.appmgr.state.*;

/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.session.EODReportApplet
 * 1. com.chelseasystems.cs.swing.pos.ParkApplet
 * 2. com.chelseasystems.cs.swing.menu.PosMenuApplet
 */
public class EndofDayApplet_EUR_State
{

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int PREV (IApplicationManager theAppMgr) throws StateException {
        //
        // put state logic here
        //
        throw  new StateException("State change not implemented->PREV");
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int CANCEL (IApplicationManager theAppMgr) throws StateException {
        if(theAppMgr.getStateObject("CASHIER_SESSION") != null)
        {
            return(2);
        }
        else
        {
            theAppMgr.goHome();
            return(-1);
        }
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int START_EOD (IApplicationManager theAppMgr) throws StateException {
        return(-1);
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int OK (IApplicationManager theAppMgr) throws StateException {
        theAppMgr.goHome();
        return(-1);
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int CLEAR_TOTALS (IApplicationManager theAppMgr) throws StateException {
        return(-1);
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int MODIFY_TOTALS (IApplicationManager theAppMgr) throws StateException {
        return(-1);
        //throw new StateException("State change not implemented->MODIFY_TOTALS");
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int PROCESS_EOD (IApplicationManager theAppMgr) throws StateException {
        //return 0;
        return(-1);
    }

    /**
     * @param theAppMgr
     * @return
     * @exception StateException
     */
    public int VERIFY_DEPOSIT (IApplicationManager theAppMgr) throws StateException {
        return(-1);
    }

    /**
     * This button does not really exist.
     */
    public int PARK (IApplicationManager theAppMgr) throws StateException {
        return(1);
    }
    public int MEDIA_TOTALS (IApplicationManager theAppMgr) throws StateException {
        return(-1);
    }

}
