/*
 * put your module comment here
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */
package com.chelseasystems.cs.swing.pos;

import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;
import com.chelseasystems.cr.config.ConfigMgr;
import com.chelseasystems.cs.util.Version;

/**
 * Comments generated by AppBuilder. Do not modify. 0. com.chelseasystems.cs.swing.pos.CustSaleApplet 1.
 * com.chelseasystems.cs.swing.pos.InitialSaleApplet 2. com.chelseasystems.cs.swing.login.InitialLoginApplet 3.
 * com.chelseasystems.cs.swing.menu.PosMenuApplet
 */
public class IdentifyConsultantApplet_State {
	/**
	 * If <code>CONSULTANT</code> exists then goto InitialSaleApplet, else goto CustSaleApplet
	 */
	public int HOUSE_ID(IApplicationManager theAppMgr) throws StateException {
		// ___Tim:Disable return to PaymentApplet after posting txn
		if (theAppMgr.getStateObject("NEW_TXN_AFTER_TENDER") != null) {
			theAppMgr.removeStateObject("NEW_TXN_AFTER_TENDER");
		}
		if (theAppMgr.getStateObject("UPDATE_TXN_ASSOCIATE") != null) {
			return 4;
		}
		if("EUR".equalsIgnoreCase(Version.CURRENT_REGION)){
		ConfigMgr configMgr = new ConfigMgr("store.cfg");
		String strMode = configMgr.getString("DUTY_FREE_SHOP");
		try{
		if(strMode.equalsIgnoreCase("TRUE")){
			theAppMgr.addStateObject("ARM_BOARDING_PASS", "TRUE");
		}
		}
		catch(NullPointerException e){}
		}
		return 1;
	}

	/**
	 * put your documentation comment here
	 * 
	 * @param theAppMgr
	 * @return
	 * @exception StateException
	 */
	public int OK(IApplicationManager theAppMgr) throws StateException {
		throw new StateException("State change not implemented->OK");
	}

	/**
	 * Goto InitialSaleApplet
	 */
	public int PREV(IApplicationManager theAppMgr) throws StateException {
		theAppMgr.goBack();
		return -1;
	}

	/**
	 * goHome
	 */
	public int CANCEL(IApplicationManager theAppMgr) throws StateException {
		if (theAppMgr.getStateObject("NEW_TXN_AFTER_TENDER") != null) {
			theAppMgr.removeStateObject("NEW_TXN_AFTER_TENDER");
		}
		if (theAppMgr.getStateObject("UPDATE_TXN_ASSOCIATE") != null) {
			return 4;
		}
		if (theAppMgr.getStateObject("ARM_REGISTER_VIP") != null) {
			theAppMgr.removeStateObject("ARM_REGISTER_VIP");
			theAppMgr.removeStateObject("CUST_MGMT_MODE");
			return 0;
		}
		if (theAppMgr.getStateObject("CONSULTANT") == null) { // came from InitialLoginApplet
			if (theAppMgr.getStateObject("CASHIER_SESSION") != null) {
				return 3;
			} else
				theAppMgr.goHome();
		} else if (theAppMgr.showOptionDlg("Cancel Transaction"// came from InitialSaleApplet
				, "Are you sure you want to cancel this transaction?")) {
			if (theAppMgr.getStateObject("CASHIER_SESSION") != null)
				return 3;
			else
				theAppMgr.goHome();
		}
		return -1; // do nothing.
	}
}
