/*
 * put your module comment here
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */


package com.chelseasystems.cs.swing.pos;

import com.chelseasystems.cs.util.Version;
import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;
import com.chelseasystems.cs.swing.menu.MenuConst;


/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.pos.ShippingDetailApplet
 */
public class ShippingHeaderApplet_State {
  private static final int ADD_MODE = 0;
  private static final int UPDATE_MODE = 1;
  private static final int INQUIRE_MODE = 2;

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int ITEMS(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    return 0;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PREV(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    //      theAppMgr.goBack();
    //Ks: returns to initialSaleApplet
    int mode = 0;
    if ("EUR".equals(Version.CURRENT_REGION)) {
	    if ((theAppMgr.getStateObject("SHIPPING_INQUIRY_ONLY") != null) || (theAppMgr.getStateObject("ADD_FROM_INQUIRY") != null)){
	      theAppMgr.removeStateObject("SHIPPING_INQUIRY_ONLY");
	      //theAppMgr.goBack();
	      return 3;
	    }
    }
    else {
        if (theAppMgr.getStateObject("SHIPPING_INQUIRY_ONLY") != null) {
            theAppMgr.removeStateObject("SHIPPING_INQUIRY_ONLY");
            theAppMgr.goBack();
            return -1;
          }
    }
    return 2;
    
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CANCEL(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    //Ks: returns to initialSaleApplet
    //      theAppMgr.goHome();
//    return -1;
    if ((theAppMgr.getStateObject("SHIPPING_INQUIRY_ONLY") != null) || (theAppMgr.getStateObject("ADD_FROM_INQUIRY") != null)){
      theAppMgr.removeStateObject("SHIPPING_INQUIRY_ONLY");
      //theAppMgr.goBack();
      return 3;
    }
    return 2;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CHANGE_ADDRESS(IApplicationManager theAppMgr)
      throws StateException {
    return 1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CLEAR(IApplicationManager theAppMgr)
      throws StateException {
    return -1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int SPECIAL_INSTRUCTIONS(IApplicationManager theAppMgr)
      throws StateException {
    return -1;
  }
}

