/*
 History:
 +------+------------+-----------+-----------+----------------------------------------------+
 | Ver# | Date       | By        | Defect #  | Description                                  |
 +------+------------+-----------+-----------+----------------------------------------------------+
 | 4    | 06-08-2005 | Vikram    | 123       |Item Return Screen flow issue                 |
 +------+------------+-----------+-----------+----------------------------------------------+
 | 3    | 05/03/2005 | Khyati    | N/A       | Cancel button to return to InitialSaleApplet |         |
 +------+------------+-----------+-----------+----------------------------------------------+
 | 2    | 04-11-2005 | Khyati    | N/A       |1.Return Specification                        |
 ---------------------------------------------------------------------------------------------
 | 1    | 04-09-2005 | Khyati    | N/A       | Base                                         |
 +------+------------+-----------+-----------+----------------------------------------------+
 *
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */


package com.chelseasystems.cs.swing.returns;

import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;
import com.chelseasystems.cs.swing.pos.InitialSaleApplet;

/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.returns.ReturnCustomerApplet
 * 1. com.chelseasystems.cs.swing.pos.InitialSaleApplet
 * 2. com.chelseasystems.cs.swing.returns.InitialReturnApplet
 */
public class OriginalConsultantApplet_State {

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CANCEL(IApplicationManager theAppMgr)
      throws StateException {
    //      theAppMgr.goHome();
    theAppMgr.removeStateObject("RETURN_COMMENTS");
    theAppMgr.removeStateObject("RETURN_REASON");
    theAppMgr.removeStateObject("RETURN_SALE");
    return 1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int HOUSE_ID(IApplicationManager theAppMgr)
      throws StateException {
    return -1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int OK(IApplicationManager theAppMgr)
      throws StateException {
    return 1;
  }

  /**
   * This button does not exist.
   */
  public int CUST(IApplicationManager theAppMgr)
      throws StateException {
    //Khyati: Added for Customer lookup Applet to redirect based on the this state object
    theAppMgr.addStateObject("ARM_DIRECT_TO", "RETURN_TO_SALE_APPLET");
    theAppMgr.addStateObject("ARM_DIRECTED_FROM", "ORIGINAL_CONSULTANT_APPLET");
//    theAppMgr.addStateObject("ARM_CUST_REQUIRED", "TRUE");
    return 0;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PREV(IApplicationManager theAppMgr)
      throws StateException {
    return 2;
  }
}

