/*
 * put your module comment here
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */


package com.chelseasystems.cs.swing.returns;

import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;


/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.pos.InitialSaleApplet
 * 1. com.chelseasystems.cs.swing.return.InitialReturnApplet
 */
public class ReturnSaleApplet_EUR_State {

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CANCEL(IApplicationManager theAppMgr)
      throws StateException {
    if (theAppMgr.getStateObject("RETURN_MODE") != null) {
      theAppMgr.removeStateObject("TXN_POS");
      theAppMgr.removeStateObject("CUSTOMER");
      return 1;
    } else {
      // DP : Return was cancelled .. returning to Initial Sale Applet ..
      // Clear all the RETURN state objects ....
      theAppMgr.removeStateObject("RETURN_COMMENTS");
      theAppMgr.removeStateObject("RETURN_REASON");
      theAppMgr.removeStateObject("RETURN_TXN_POS");
      return 0;
    }
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int DE_SELECT_ALL(IApplicationManager theAppMgr)
      throws StateException {
    return -1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int OK(IApplicationManager theAppMgr)
      throws StateException {
    theAppMgr.removeStateObject("RETURN_COMMENTS");
    theAppMgr.removeStateObject("RETURN_REASON");
    theAppMgr.removeStateObject("RETURN_TXN_POS");
    return 0;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PREV(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    throw new StateException("State change not implemented->PREV");
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int SELECT_ALL(IApplicationManager theAppMgr)
      throws StateException {
    return -1;
  }
}

