/*
 * put your module comment here
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */


package com.chelseasystems.cs.swing.transaction;

import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;


/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.pos.InitialSaleApplet
 * 1. com.chelseasystems.cs.swing.return.InitialReturnApplet
 * 5. com.chelseasystems.cs.swing.transaction.CustomerAsisTxnHistoryApplet
 */
public class ASISTxnDataApplet_State {

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CANCEL(IApplicationManager theAppMgr)
      throws StateException {
    if (theAppMgr.getStateObject("FROM_INITIAL_SALE_APPLET") != null) {
      theAppMgr.removeStateObject("FROM_INITIAL_SALE_APPLET");
      return 1;
    } else if (theAppMgr.getStateObject("FROM_PAID_IN") != null) {
      theAppMgr.removeStateObject("FROM_PAID_IN");
      return 2;
    } else if (theAppMgr.getStateObject("FROM_PAID_OUT") != null) {
      theAppMgr.removeStateObject("FROM_PAID_OUT");
      return 3;
    } else {
      return 0;
    }
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int OK(IApplicationManager theAppMgr)
      throws StateException {
    theAppMgr.removeStateObject("THE_TXN");
    if (theAppMgr.getStateObject("FROM_INITIAL_SALE_APPLET") != null) {
      theAppMgr.removeStateObject("FROM_INITIAL_SALE_APPLET");
      return 1;
    } else if (theAppMgr.getStateObject("FROM_PAID_IN") != null) {
      theAppMgr.removeStateObject("FROM_PAID_IN");
      return 2;
    } else if (theAppMgr.getStateObject("FROM_PAID_OUT") != null) {
      theAppMgr.removeStateObject("FROM_PAID_OUT");
      return 3;
    } else {
      return 0;
    }
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CUSTOMER_LOOKUP(IApplicationManager theAppMgr)
      throws StateException {
    theAppMgr.addStateObject("ARM_DIRECTED_FROM", "ASIS_TXN_APPLET");
    theAppMgr.addStateObject("ARM_DIRECT_TO", "ASIS_TXN_APPLET");
    theAppMgr.addStateObject("ARM_CUST_REQUIRED", "TRUE");
    return 4;
  }


  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int TRANSACTION_HISTORY(IApplicationManager theAppMgr)
      throws StateException {
    return 5;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PREV(IApplicationManager theAppMgr)
      throws StateException {
	  if (theAppMgr.getStateObject("FROM_TXN_DETAIL_APPLET") != null) {
		  theAppMgr.removeStateObject("FROM_TXN_DETAIL_APPLET");
	  }
	  theAppMgr.goBack();
	  return -1;
  }
}

