/*
 * put your module comment here
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */


package com.chelseasystems.cs.swing.paidouts;

import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;


/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.pos.PaymentApplet
 */
public class PaidoutApplet_State {

  /**
   * put your documentation comment here
   */
  public PaidoutApplet_State() {
    try {
      jbInit();
    } catch (Exception ex) {
      ex.printStackTrace();
    }
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CANCEL(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    theAppMgr.goHome();
    if (true)
      return -1;
    else
      throw new StateException("State change not implemented->CANCEL");
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int OK(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    System.out.println("in state code for OK");
    theAppMgr.removeStateObject("REASON_CODE");
    return 0;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int OK_COLLECTIONS(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    System.out.println("in state code for OK");
    theAppMgr.removeStateObject("REASON_CODE");
    theAppMgr.removeStateObject("CUSTOMER_ASIS");
    return 0;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PREV(IApplicationManager theAppMgr)
      throws StateException {
    //ks: goBack is not right, it may go back to PaymentApplet. Update model and enforcing back to TransactionManagementApplet
    //      theAppMgr.goBack();
    theAppMgr.removeStateObject("REASON_CODE");
    theAppMgr.removeStateObject("CUSTOMER_ASIS");
    return 1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int ADD_ASIS(IApplicationManager theAppMgr)
      throws StateException {
    return 2;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CUST_LOOKUP(IApplicationManager theAppMgr)
      throws StateException {
    theAppMgr.addStateObject("ARM_DIRECT_TO", "COLLECTIONS_APPLET");
    theAppMgr.addStateObject("ARM_DIRECTED_FROM", "COLLECTIONS_APPLET");
    theAppMgr.addStateObject("ARM_CUST_REQUIRED", "TRUE");
    return 3;
  }

  /**
   * put your documentation comment here
   * @exception Exception
   */
  private void jbInit()
      throws Exception {}
}

