/*
 History:
 +------+------------+-----------+-----------+-------------------------------------------------+
 | Ver# | Date       | By        | Defect #  | Description                                     |
 +------+------------+-----------+-----------+-------------------------------------------------+
 | 2    | 04-28-2005 |Khayti     |           | Store Close Out                                                |
 -----------------------------------------------------------------------------------------------
 *
 * formatted with JxBeauty (c) johann.langhofer@nextra.at
 */


package com.chelseasystems.cs.swing.menu;

import com.chelseasystems.cr.appmgr.*;
import com.chelseasystems.cr.appmgr.state.*;


/**
 * Comments generated by AppBuilder. Do not modify.
 * 0. com.chelseasystems.cs.swing.paidouts.PaidoutApplet
 * 1. com.chelseasystems.cs.swing.collections.CollectionsApplet
 * 2. com.chelseasystems.cs.swing.transaction.VoidTransactionApplet
 * 3. com.chelseasystems.cs.swing.menu.InitialMgmtMenuApplet
 * 4. com.chelseasystems.cs.swing.transaction.RedeemableBuyBackApplet
 */
/*
 History:
 +------+------------+-----------+-----------+----------------------------------------------+
 | Ver# | Date       | By        | Defect #  | Description                                  |
 +------+------------+-----------+-----------+----------------------------------------------+
 | 1    | 04-22-2005 | Mukesh    | N/A       |1.Change the name of VOID_TRXN method to      |
 |      |            |           |           | POST_VOID in the void trxn changes.          |
 --------------------------------------------------------------------------------------------
 */
public class TransactionMgmtMenuApplet_State {

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int CANCEL(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    throw new StateException("State change not implemented->CANCEL");
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int COLLECTIONS(IApplicationManager theAppMgr)
      throws StateException {
    return 1;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int OK(IApplicationManager theAppMgr)
      throws StateException {
    //
    // put state logic here
    //
    throw new StateException("State change not implemented->OK");
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PAIDOUTS(IApplicationManager theAppMgr)
      throws StateException {
    return 0;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int PREV(IApplicationManager theAppMgr)
      throws StateException {
    return 3;
  }

  /*This method name modified to POST_VOID from VOID_TRXN to implement the changes of void trxn
   @author Mukesh
   */
  public int POST_VOID(IApplicationManager theAppMgr)
      throws StateException {
    return 2;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int BUY_BACK(IApplicationManager theAppMgr)
      throws StateException {
    return 4;
  }

  /**
   * put your documentation comment here
   * @param theAppMgr
   * @return
   * @exception StateException
   */
  public int END_DAY(IApplicationManager theAppMgr)
      throws StateException {
    return 6;
  }
}

